apiVersion: v1
kind: Service
metadata:
  name: hello-web-service
spec:
  type: NodePort  # <-- เปลี่ยนตรงนี้
  # ลบ loadBalancerIP ทิ้งไปเลย
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80         # Port ภายในที่ Ingress จะคุยด้วย
    targetPort: 8080 # Port ของ App (Container)